#!/usr/bin/env ruby

# frozen_string_literal: true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")

require "tablature_hero"

def play(filename)
  path = File.join(File.dirname(__FILE__), "..", "media", filename)
  `afplay #{path}.mp3`
end

puts "running tablature_hero #{TablatureHero::VERSION}"
tempo = ARGV.shift.chomp
beat_duration = 60.0 / tempo.to_i
begin
  loop do
    Thread.new { play("metro_high") }
    sleep beat_duration
    3.times do
      Thread.new { play("metro_low") }
      sleep beat_duration
    end
  end
rescue Interrupt
  puts "...exiting"
end
