#!/usr/bin/env ruby

# frozen_string_literal: true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")

require "tablature_hero"

song = [
  {
    tempo: 60,
    time_signature: "4/4",
    bars: [
      [
        { string: "e" },
        { string: "B", notes: [{ fret: 0, duration: 4 }] },
        { string: "G", notes: [{ fret: 0, duration: 2 }, { fret: 0, duration: 2 }] },
        { string: "D" },
        { string: "E" },
      ],
      [
        { string: "e" },
        { string: "B", notes: [{ fret: 0, duration: 4 }] },
        { string: "G", notes: [{ fret: 0, duration: 2 }, { fret: 0, duration: 2 }] },
        { string: "D" },
        { string: "E" },
      ],
    ]
  },
  {
    tempo: 90,
    time_signature: "3/4",
    bars: [
      [
        { string: "e" },
        { string: "B", notes: [{ fret: 0, duration: 4 }] },
        { string: "G", notes: [{ fret: 0, duration: 2 }, { fret: 0, duration: 2 }] },
        { string: "D" },
        { string: "E" },
      ],
      [
        { string: "e" },
        { string: "B", notes: [{ fret: 0, duration: 4 }] },
        { string: "G", notes: [{ fret: 0, duration: 2 }, { fret: 0, duration: 2 }] },
        { string: "D" },
        { string: "E" },
      ],
    ]
  },
]

TablatureHero::Display.start(song)